# example workflow for SRM scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: srm
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  srm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: SRM Scan
      uses: synopsys-sig/synopsys-action@v1.12.0
      with:
        srm_url: ${{ vars.SRM_URL }}
        srm_apikey: ${{ secrets.SRM_APIKEY }}
        srm_assessment_types: 'SAST,SCA'
        srm_project_name: ${{ github.event.repository.name }}
        srm_branch_name: ${{ github.event.ref_name }}
        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
